build.rs: Manually pass the host to bindgen clang
In order to avoid errors like this when cross compiling:

    error: unknown target triple 'riscv32imc-unknown-none-elf', please use -triple or -arch

we pass the host target to clang instead of the target.

See https://github.com/rust-lang/rust-bindgen/issues/1728 for the
upstream issue.

Signed-off-by: Alistair Francis <alistair.francis@wdc.com>